db_path: "backend/stock.db"
kline_days: 120
update_hour: 12
update_minute: 56
combination: "all"
# worker pool defaults for startup watchlist KLine fetch
worker_concurrency: 5
worker_retries: 3
worker_delay_ms: 200
worker_backoff_ms: 500
watchlist_kline_days: 300
strategies:
  - name: "MA"
    enabled: true
    params:
      ma: 20
      hold_days: 3
  - name: "MACD"
    enabled: true
  - name: "Composite"
    enabled: true
    params:
      hold_days: 3
  - name: "DSL"
    enabled: true
    params:
      expr: "close > ma20 AND macd_dif > macd_dea"
